### ISSUE TITLE
I can't able to open that webvi using LabVIEW NXG 2.1

### ISSUE THREAD

**Issue by Joel12131** [ni/webvi-examples#112]
** Instructions **
This issue tracker is intended to report bugs in the examples such as typos, broken links, etc.

The issue tracker should *NOT* be used for asking for help, making feature suggestions, etc. To ask for help or give general feedback please post in the LabVIEW NXG section of the LabVIEW Discussion Forums:
https://forums.ni.com/t5/LabVIEW/bd-p/170

**Comment by rajsite** [comment]
Hi Joel12131,

As can be found in the [README](https://github.com/ni/webvi-examples/blob/master/Readme.md) the repository is currently targeting LabVIEW NXG 5.0.

The examples ship in LabVIEW NXG and can be found by doing the following:

![NXGExampleLocation](https://user-images.githubusercontent.com/1588923/87692476-6a6c9200-c751-11ea-8bb5-722d73b49cf1.gif)

You can also look at the previous releases from this repository to [download](https://github.com/ni/webvi-examples/releases/tag/nxg2) the examples from that time.
