### ISSUE TITLE
Example with a Login

### ISSUE THREAD

**Issue by andcell** [ni/webvi-examples#115]
Hello!

is it possible to have an example with the possibility to secure the web panel with a login with user&password request?

thank you very much.
Andrea

**Comment by rajsite** [comment]
Hi Andrea,

This issue tracker is intended to report bugs in the examples such as typos, broken links, etc.

The webvi-examples issue tracker should not be used for asking for help, making feature suggestions, etc. To ask for help or give general feedback please post in the LabVIEW NXG section of the [LabVIEW Discussion Forums](https://forums.ni.com/t5/LabVIEW/bd-p/170).

If you are using the latest version of SystemLink with WebVIs a [WebVI Hosting](https://www.ni.com/documentation/en/systemlink/latest/deployment/hosting-a-web-vi/) feature has been included that allows configuration of access to WebVIs with a username and password. If you are using LabVIEW NXG Web Module and hosting on the NI Web Server you can turn the [WebVI into a plugin](https://github.com/ni/systemlink-web-interface-template) and configure access with a username and password.

If you have additional questions please post in the [LabVIEW Discussion Forums](https://forums.ni.com/t5/LabVIEW/bd-p/170) or contact NI Support. I will go ahead and close this issue as it does not report a bug in the examples.
