### ISSUE TITLE
Call LabVIEW Web Service fails for Elevated Permissions but doesn't give the prompt

### ISSUE THREAD

**Issue by N-Powl** [ni/webvi-examples#117]
The Call LabVIEW Web Service example project, WebService.lvproj, won't allow for the Web Server to be started:
_There was an error running the web service on the debug server: Error -1967362033 occurred at NI Web Service Provider.lvlib:Elevated Copy.vi

Possible reason(s):

OS and Network Services: (Hex 0x8ABC700F) Invalid argument(s).

Complete call chain:
     NI Web Service Provider.lvlib:Elevated Copy.vi
     NI Web Service Debug.lvlib:Copy Public Folder.vi
     NI Web Service Debug.lvlib:Copy Configs.vi
     NI Web Service Debug.lvlib:Debug Web Service.vi
     NI Web Service Debug.lvlib:Launch_WS_Debug.vi
     NI Web Service Debug.lvlib:Launch_WS_Debug.vi.ProxyCaller_

Recreating the Web Server prompts to give elevated permissions correctly. 

Additionally, it looks like the Public Content auto-populating folder is missing and the published web article does not update when the GET/POST requests are submitted.

**Comment by rajsite** [comment]
These issues should be resolved in main and in the examples in G Web Development Software.
