### ISSUE TITLE
vireo-source="WebVI/Builds/WebApp_Web%20Server/Main.via.txt" can't work.

### ISSUE THREAD

**Issue by jl7086ws** [ni/webvi-examples#36]
Edge will access follow url:
http://localhost/webvi-example/WebVI%2FBuilds%2FWebApp_Web%2520Server%2FMain.via.txt
Console log:

 HTTP404: 找不到 - 服务器尚未找到与请求的 URI (统一资源标识符)匹配的任何内容。
(XHR)GET - http://localhost/webvi-example/WebVI%2FBuilds%2FWebApp_Web%2520Server%2FMain.via.txt

 Error retrieving vireo source from url ( WebVI/Builds/WebApp_Web%20Server/Main.via.txt ) with status ( error ) 
niModelsAndViewModels.min.js (1,28895)

**Comment by prestwick** [comment]
Just use a space character rather than %20 and it should work.

**Comment by rajsite** [comment]
The workaround described by @prestwick should work around the behavior.
We have made a change that should prevent the problem in the next major release.
