### ISSUE TITLE
How can I quickly find the css information about one control in html??

### ISSUE THREAD

**Issue by zht01** [ni/webvi-examples#42]

**Comment by rajsite** [comment]
Hi @zht01, a bit of a late reply but in-case anyone else is curious we do not currently expose documentation for CSS information on WebVIs in LabVIEW NXG 2.

The controls we are working on and the styles used to write them are still changing heavily, so if you were to make styles today there is no guarantee they will behave correctly in future versions of LabVIEW NXG.

When we have a good CSS style approach, we will share documentation at that time.

If you have further questions about WebVIs the best place to ask in the LabVIEW discussion forums: https://forums.ni.com/t5/LabVIEW/bd-p/170
