### ISSUE TITLE
How to remotely access a web application developed by LabVIEW NXG and standard LabVIEW web service?

### ISSUE THREAD

**Issue by curioushuman4** [ni/webvi-examples#83]
I have tried understanding and working on one of the ni webvi examples as shown in GitHub. Below is the example link:
https://github.com/ni/webvi-examples/tree/master/CallLabVIEWWebService

The first issue, I faced was to communicate LabVIEW NXG 2.1 and Standard LabVIEW 2018. The issue was due to using tow different ports i.e. 8080 for debug port in LabVIEW 2018 and port 8001 in LabVIEW NXG 2.1. It was throwing an error of CORS origin or the client was not able to reach the target server. Finally I solved the issue by using an unsed port say 5007 for both the applications and it worked fine!  Also I am able to build and run the web application in any browser in my local PC.
Now I am facing two issues here:

1.  I have followed the 'Setup' steps as mentioned in the example in GitHub.
 If I run the Main.gviweb in NXG and then go to WebApp.gcomp and build it. The build fails by giving a error with the message 'dependency is currently running'. Then, I am not able to access the web application in the web.
However, once i run the Main.gviweb and stop it. After halting it's execution and then trying to build it, this time it works.
Can someone tell me why this happens? Why can't I run the gviweb and then build?Why should i first stop ist execution and then build it?

2.  I want to host the web application in a remote system connected with the same network as the local PC (where the LabVIEW webservice is running). I have tried with the follwing url, but I am not able to access it remotely:
http://lPaddress_of_local_PC/WebApp_Web%20Server/Main.html

Can someone tell how I can acccess the link from any remote system?

**Comment by rajsite** [comment]
Hi @curioushuman4,

Thanks for getting in touch. Unfortunately this issue tracker is not a great place to ask for help but is instead intended for reporting bugs, typos, broken urls etc.

The best place to ask questions is in the LabVIEW community forums. It looks like you have already cross-posted this question in the LabVIEW community here: https://forums.ni.com/t5/LabVIEW/How-to-remotely-access-a-web-application-developed-by-LabVIEW/m-p/3885762?lang=en

So I'm going to go ahead and close this issue. Thanks!
